name: Python application

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: tiangolo/docker-with-compose

    env:
      BUILDKIT_INLINE_CACHE: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      DOCKER_IMAGE_BACKEND: gcr.io/${{ secrets.GCP_PROJECT_ID }}/buildkit-test

    steps:
    - uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Docker login
      run: |
        gcloud auth configure-docker

    - name: Build docker images
      run: |
        export BRANCH_NAME=master
        export SHA=$GITHUB_SHA
        echo $SHA, $BRANCH_NAME
        docker build backend --progress=plain -t $DOCKER_IMAGE_BACKEND:$SHA --cache-from $DOCKER_IMAGE_BACKEND:$BRANCH_NAME --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg INSTALL_DEV=true
        docker tag $DOCKER_IMAGE_BACKEND:$SHA $DOCKER_IMAGE_BACKEND:$BRANCH_NAME
        docker push $DOCKER_IMAGE_BACKEND:$BRANCH_NAME
        docker run $DOCKER_IMAGE_BACKEND:$BRANCH_NAME python test.py
